apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-v1
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo
      version: v1
  template:
    metadata:
      labels:
        app: podinfo
        version: v1
    spec:
      enableServiceLinks: false
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:6.7.0
          ports:
            - name: http
              containerPort: 9898
          env:
            - name: PODINFO_UI_MESSAGE
              value: "VERSION ONE"
            - name: PODINFO_UI_COLOR
              value: "#30BA78"
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-v1
  namespace: demo
spec:
  selector:
    app: podinfo
    version: v1
  ports:
    - name: http
      port: 9898
      targetPort: http
